/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package datastructproject;

import javax.swing.JOptionPane;

/**
 *
 * @author yapyu
 */
public class GUI extends javax.swing.JFrame {

    static int count = 0;
    static Node head = new Node();
    static Node current = new Node();
    static Node before = new Node();
    static String target = "";

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        displayButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        locInput = new javax.swing.JTextField();
        facInput = new javax.swing.JTextField();
        actInput = new javax.swing.JTextField();
        durInput = new javax.swing.JTextField();
        budInput = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        targetInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vacation Recomender");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        displayButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        displayButton.setText("Display");
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jButton6.setText("Exit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Display Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        displayOutput.setColumns(20);
        displayOutput.setRows(5);
        jScrollPane1.setViewportView(displayOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Location");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Facilities");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Activities");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Budget");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Duration (Days)");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Edit Section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Location:");

        deleteButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addComponent(targetInput, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(targetInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(searchButton))
                .addGap(24, 24, 24))
        );

        updateButton.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton))
                    .addComponent(durInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(budInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facInput, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(locInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(facInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(actInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(budInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(durInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(displayButton))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        String location = locInput.getText();
        String fac = facInput.getText();
        String activity = actInput.getText();
        double budget = Double.parseDouble(budInput.getText());
        int days = Integer.parseInt(durInput.getText());

        Vacay vacay = new Vacay(location, activity, fac, budget, days);

        Node newNode = new Node(vacay);

        if (head.getInfo() == null) {
            head = newNode;
        } else {
            current = head;
            // traversing nodes
            while (current.getLink() != null) // current.link != null
            {
                current = current.getLink(); // current = current.link
            }
            current.setLink(newNode); // current.link= newNode
        }
        count++;
        System.out.println(head.getInfo());

        locInput.setText("");
        facInput.setText("");
        actInput.setText("");
        budInput.setText("");
        durInput.setText("");

        current = head;
        String output = "";
        String finalOutput = "";

        if (current == null) {
            displayOutput.setText("empty");
        }
        String title = String.format("%1$-50s%2$-30s%3$-30s%4$-20s%5$-20s%n", "Location", "Facilities", "Activity", "Budget(RM)", "Duration(Days)");
        String header = "=========================================================================================\n";
        while (current != null) {

            output = String.format("%1$-50s%2$-38s%3$-30s%4$-20.2f%5$-20s%n", current.getInfo().getLocation(), current.getInfo().getFac(), current.getInfo().getActivity(), current.getInfo().getBudget(), current.getInfo().getDays());
            finalOutput += output;
            current = current.getLink();
        }

        displayOutput.setText(title + header + finalOutput);


    }//GEN-LAST:event_addButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        target = targetInput.getText();

        if (head.getInfo().getLocation().equals(target)) {
            current = head;
            String output = "";
            String finalOutput = "";

            if (current == null) {
                displayOutput.setText("empty");
            }
            String title = String.format("%1$-50s%2$-30s%3$-30s%4$-20s%5$-20s%n", "Location", "Facilities", "Activity", "Budget(RM)", "Duration(Days)");
            String header = "=========================================================================================\n";

            output = String.format("%1$-50s%2$-38s%3$-30s%4$-20.2f%5$-20s%n", current.getInfo().getLocation(), current.getInfo().getFac(), current.getInfo().getActivity(), current.getInfo().getBudget(), current.getInfo().getDays());
            displayOutput.setText(title + header + output);

        } else {
            before = null;
            current = head;

            // current.info != target
            while ((!current.getInfo().getLocation().equals(target)) && (current != null)) {
                if (!current.getInfo().getLocation().equals(target)) {
                    before = current;
                    current = before.getLink();
                }// current = current.link
            }
            if (current.getInfo().getLocation().equals(target)) {  // current.info == target

                String output = "";
                String finalOutput = "";

                if (current == null) {
                    displayOutput.setText("empty");
                }
                String title = String.format("%1$-50s%2$-30s%3$-30s%4$-20s%5$-20s%n", "Location", "Facilities", "Activity", "Budget(RM)", "Duration(Days)");
                String header = "=========================================================================================\n";

                output = String.format("%1$-50s%2$-38s%3$-30s%4$-20.2f%5$-20s%n", current.getInfo().getLocation(), current.getInfo().getFac(), current.getInfo().getActivity(), current.getInfo().getBudget(), current.getInfo().getDays());
                displayOutput.setText(title + header + output);

            } else {
                System.out.println("The target is not exists");
            }
        }

        System.out.println(current.getInfo());


    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        target = targetInput.getText();
        System.out.println(target);

        String location = locInput.getText();
        String fac = facInput.getText();
        String activity = actInput.getText();
        double budget = Double.parseDouble(budInput.getText());
        int days = Integer.parseInt(durInput.getText());

        Vacay vacay = new Vacay(location, activity, fac, budget, days);

        if (head.getInfo().getLocation().equals(target)) {
            head.setInfo(vacay);

        } else {
            before = null;
            current = head;

            // current.info != target
            while ((!current.getInfo().getLocation().equals(target)) && (current != null)) {
                if (!current.getInfo().getLocation().equals(target)) {
                    before = current;
                    current = before.getLink();
                }// current = current.link
            }
            if (current.getInfo().getLocation().equals(target)) {  // current.info == target
                current.setInfo(vacay);
            } else {
                System.out.println("The target is not exists");
            }
        }

        current = head;
        String output = "";
        String finalOutput = "";

        if (current == null) {
            displayOutput.setText("empty");
        }
        String title = String.format("%1$-50s%2$-30s%3$-30s%4$-20s%5$-20s%n", "Location", "Facilities", "Activity", "Budget(RM)", "Duration(Days)");
        String header = "=========================================================================================\n";
        while (current != null) {

            output = String.format("%1$-50s%2$-38s%3$-30s%4$-20.2f%5$-20s%n", current.getInfo().getLocation(), current.getInfo().getFac(), current.getInfo().getActivity(), current.getInfo().getBudget(), current.getInfo().getDays());
            finalOutput += output;
            current = current.getLink();
        }

        displayOutput.setText(title + header + finalOutput);


    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        target = targetInput.getText();

        if (head.getInfo().getLocation().equals(target)) {
            head = head.getLink();
        } else {
            before = null;
            current = head;

            // current.info != target
            while ((!current.getInfo().getLocation().equals(target)) && (current != null)) {

                before = current;
                current = before.getLink();
                // current = current.link
            }
            if (current.getInfo().getLocation().equals(target)) {  // current.info == target
                before.setLink(current.getLink());

            } else {
                System.out.println("Target no found");
            }
        }

        String output = "";
        String finalOutput = "";
        String title = String.format("%1$-50s%2$-30s%3$-30s%4$-20s%5$-20s%n", "Location", "Facilities", "Activity", "Budget(RM)", "Duration(Days)");
        String header = "=========================================================================================\n";
        current = head;

        while (current != null) {

            output = String.format("%1$-50s%2$-38s%3$-30s%4$-20.2f%5$-20s%n", current.getInfo().getLocation(), current.getInfo().getFac(), current.getInfo().getActivity(), current.getInfo().getBudget(), current.getInfo().getDays());
            finalOutput += output;
            current = current.getLink();
        }

        displayOutput.setText(title + header + finalOutput);


    }//GEN-LAST:event_deleteButtonActionPerformed

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed

        current = head;
        String output = "";
        String finalOutput = "";

        if (current == null) {
            displayOutput.setText("empty");
        }
        String title = String.format("%1$-50s%2$-30s%3$-30s%4$-20s%5$-20s%n", "Location", "Facilities", "Activity", "Budget(RM)", "Duration(Days)");
        String header = "=========================================================================================\n";
        while (current != null) {

            output = String.format("%1$-50s%2$-38s%3$-30s%4$-20.2f%5$-20s%n", current.getInfo().getLocation(), current.getInfo().getFac(), current.getInfo().getActivity(), current.getInfo().getBudget(), current.getInfo().getDays());
            finalOutput += output;
            current = current.getLink();
        }

        displayOutput.setText(title + header + finalOutput);

    }//GEN-LAST:event_displayButtonActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actInput;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField budInput;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton displayButton;
    private javax.swing.JTextArea displayOutput;
    private javax.swing.JTextField durInput;
    private javax.swing.JTextField facInput;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField locInput;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField targetInput;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
